# Generated by Django 5.2.6 on 2026-02-24 21:53

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('auth', '0012_alter_user_first_name_max_length'),
    #     ('universites', '0008_remove_news_publisher_remove_oldstudent_publisher_and_more'),
    # ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur'), ('bigboss', 'BIGBOSS')], default='standard', max_length=10, validators=[django.core.validators.RegexValidator(message='Rôle inconnu.', regex='^(standard|admin|superadmin|bigboss)$')])),
                ('realisation_linkedin', models.URLField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profil/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('standard', 'Standard'), ('professeur', 'Professeur'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur'), ('bigboss', 'BIGBOSS')], default='standard', max_length=20)),
                ('created_by_id', models.IntegerField(verbose_name='Créé par (ID)')),
                ('created_by_email', models.EmailField(max_length=254, verbose_name='Créé par (email)')),
                ('used_by_id', models.IntegerField(blank=True, null=True, verbose_name='Utilisé par (ID)')),
                ('used_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Utilisé par (email)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 3, 3, 21, 53, 48, 651060, tzinfo=datetime.timezone.utc))),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='universites.universite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='ID Utilisateur')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email utilisateur')),
                ('user_role', models.CharField(blank=True, max_length=20, verbose_name='Rôle utilisateur')),
                ('action', models.CharField(choices=[('MEMOIRE_CREATE', 'Création de mémoire'), ('MEMOIRE_UPDATE', 'Modification de mémoire'), ('MEMOIRE_DELETE', 'Suppression de mémoire'), ('MEMOIRE_DELETE_TOTAL', 'Suppression totale de mémoire'), ('USER_ROLE_UPDATE', 'Modification de rôle utilisateur'), ('USER_REMOVE', 'Retrait utilisateur université'), ('USER_DEACTIVATE', 'Désactivation compte'), ('USER_BULK_INVITE', 'Invitation en masse'), ('COMMENT_MODERATE', 'Modération commentaire'), ('COMMENT_DELETE', 'Suppression commentaire'), ('SIGNALEMENT_TRAITE', 'Signalement traité'), ('UNIV_LOGO_UPDATE', 'Mise à jour logo'), ('UNIV_LOGO_DELETE', 'Suppression logo'), ('UNIV_BULK_DELETE', 'Suppression multiple universités'), ('UNIV_AFFILIATION_CREATE', 'Création affiliation'), ('DOMAINE_CREATE', 'Création domaine'), ('DOMAINE_UPDATE', 'Modification domaine'), ('DOMAINE_DELETE', 'Suppression domaine'), ('NEWS_CREATE', 'Création news'), ('NEWS_DELETE', 'Suppression news'), ('NEWS_DISSOCIATE', 'Dissociation news'), ('OLDSTUDENT_CREATE', 'Création ancien étudiant'), ('OLDSTUDENT_DELETE', 'Suppression ancien étudiant'), ('OLDSTUDENT_DISSOCIATE', 'Dissociation ancien étudiant'), ('ENCADREMENT_ADD', 'Ajout encadreur'), ('ENCADREMENT_REMOVE', 'Retrait encadreur'), ('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Échec connexion'), ('PASSWORD_RESET', 'Réinitialisation mot de passe')], max_length=30, verbose_name="Type d'action")),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=10, verbose_name='Sévérité')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='Type de cible')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='ID cible')),
                ('target_repr', models.TextField(blank=True, verbose_name='Représentation cible')),
                ('previous_data', models.JSONField(blank=True, null=True, verbose_name='Données avant action')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Données après action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_path', models.TextField(blank=True, verbose_name='Chemin de la requête')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Méthode HTTP')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='universites.universite', verbose_name='Université concernée')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='users_audit_action_9b343e_idx'), models.Index(fields=['user_id', 'created_at'], name='users_audit_user_id_0bc804_idx'), models.Index(fields=['university', 'created_at'], name='users_audit_univers_01caec_idx'), models.Index(fields=['severity', 'created_at'], name='users_audit_severit_6437a2_idx'), models.Index(fields=['target_type', 'target_id'], name='users_audit_target__15185f_idx'), models.Index(fields=['created_at'], name='users_audit_created_6518da_idx')],
            },
        ),
    ]
