# Generated by Django 5.2.6 on 2026-02-25

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('universites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(
                    choices=[
                        ('standard', 'Standard'),
                        ('professeur', 'Professeur'),
                        ('admin', 'Administrateur'),
                        ('superadmin', 'Super Administrateur'),
                        ('bigboss', 'BIGBOSS')
                    ],
                    default='standard',
                    max_length=20
                )),
                ('created_by_id', models.IntegerField(verbose_name='Créé par (ID)')),
                ('created_by_email', models.EmailField(max_length=254, verbose_name='Créé par (email)')),
                ('used_by_id', models.IntegerField(blank=True, null=True, verbose_name='Utilisé par (ID)')),
                ('used_by_email', models.EmailField(blank=True, max_length=254, verbose_name='Utilisé par (email)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=users.models.InvitationCode.default_expiration)),
                ('universite', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='invitation_codes',
                    to='universites.universite'
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]