# Generated by Django 5.2.6 on 2025-12-03 18:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 10, 18, 32, 13, 867286, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_used', to=settings.AUTH_USER_MODEL),
        ),
    ]
