# Generated by Django 5.2.6 on 2026-02-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'), 
        ('universites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='ID Utilisateur')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email utilisateur')),
                ('user_role', models.CharField(blank=True, max_length=20, verbose_name='Rôle utilisateur')),
                ('action', models.CharField(max_length=30, verbose_name="Type d'action")),
                ('severity', models.CharField(
                    choices=[
                        ('LOW', 'Faible'),
                        ('MEDIUM', 'Moyenne'),
                        ('HIGH', 'Élevée'),
                        ('CRITICAL', 'Critique')
                    ],
                    default='MEDIUM',
                    max_length=10
                )),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('target_repr', models.TextField(blank=True)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='audit_logs',
                    to='universites.universite'
                )),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]