# Generated by Django 5.2.6 on 2025-12-04 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invitationcode_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 11, 0, 32, 53, 171092, tzinfo=datetime.timezone.utc)),
        ),
    ]
