# Generated by Django 5.2.6 on 2025-12-09 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_invitationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 16, 5, 54, 0, 310344, tzinfo=datetime.timezone.utc)),
        ),
    ]
