# Generated by Django 5.2.6 on 2025-12-10 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_invitationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 12, 31, 19, 775588, tzinfo=datetime.timezone.utc)),
        ),
    ]
