# Generated by Django 5.2.6 on 2025-12-13 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_invitationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 20, 4, 23, 51, 243326, tzinfo=datetime.timezone.utc)),
        ),
    ]
