# Generated by Django 5.2.6 on 2025-12-23 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_invitationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 30, 20, 27, 19, 942156, tzinfo=datetime.timezone.utc)),
        ),
    ]
