# Generated by Django 5.2.6 on 2025-12-25 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_invitationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 1, 15, 13, 4, 780307, tzinfo=datetime.timezone.utc)),
        ),
    ]
