# Generated by Django 5.2.6 on 2025-12-30 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_invitationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 6, 23, 5, 4, 733354, tzinfo=datetime.timezone.utc)),
        ),
    ]
