# Generated by Django 5.2.6 on 2026-01-07 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_invitationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 14, 19, 15, 18, 84979, tzinfo=datetime.timezone.utc)),
        ),
    ]
