# Generated by Django 5.2.6 on 2026-02-20 15:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universites', '0008_remove_news_publisher_remove_oldstudent_publisher_and_more'),
        ('users', '0019_alter_invitationcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 15, 23, 39, 656375, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email utilisateur (snapshot)')),
                ('user_role', models.CharField(blank=True, max_length=20, verbose_name='Rôle utilisateur (snapshot)')),
                ('action', models.CharField(choices=[('MEMOIRE_CREATE', 'Création de mémoire'), ('MEMOIRE_UPDATE', 'Modification de mémoire'), ('MEMOIRE_DELETE', 'Suppression de mémoire'), ('MEMOIRE_DELETE_TOTAL', 'Suppression totale de mémoire'), ('USER_ROLE_UPDATE', 'Modification de rôle utilisateur'), ('USER_REMOVE', 'Retrait utilisateur université'), ('USER_DEACTIVATE', 'Désactivation compte'), ('USER_BULK_INVITE', 'Invitation en masse'), ('COMMENT_MODERATE', 'Modération commentaire'), ('COMMENT_DELETE', 'Suppression commentaire'), ('SIGNALEMENT_TRAITE', 'Signalement traité'), ('UNIV_LOGO_UPDATE', 'Mise à jour logo'), ('UNIV_LOGO_DELETE', 'Suppression logo'), ('UNIV_BULK_DELETE', 'Suppression multiple universités'), ('UNIV_AFFILIATION_CREATE', 'Création affiliation'), ('DOMAINE_CREATE', 'Création domaine'), ('DOMAINE_UPDATE', 'Modification domaine'), ('DOMAINE_DELETE', 'Suppression domaine'), ('NEWS_CREATE', 'Création news'), ('NEWS_DELETE', 'Suppression news'), ('NEWS_DISSOCIATE', 'Dissociation news'), ('OLDSTUDENT_CREATE', 'Création ancien étudiant'), ('OLDSTUDENT_DELETE', 'Suppression ancien étudiant'), ('OLDSTUDENT_DISSOCIATE', 'Dissociation ancien étudiant'), ('ENCADREMENT_ADD', 'Ajout encadreur'), ('ENCADREMENT_REMOVE', 'Retrait encadreur'), ('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Échec connexion'), ('PASSWORD_RESET', 'Réinitialisation mot de passe')], max_length=30, verbose_name="Type d'action")),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=10, verbose_name='Sévérité')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='Type de cible')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='ID cible')),
                ('target_repr', models.TextField(blank=True, verbose_name='Représentation lisible de la cible')),
                ('previous_data', models.JSONField(blank=True, null=True, verbose_name='Données avant action')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='Données après action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_path', models.TextField(blank=True, verbose_name='Chemin de la requête')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='Méthode HTTP')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='universites.universite', verbose_name='Université concernée')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_realisees', to='users.auditlog', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='users_audit_action_9b343e_idx'), models.Index(fields=['user', 'created_at'], name='users_audit_user_id_0bc804_idx'), models.Index(fields=['university', 'created_at'], name='users_audit_univers_01caec_idx'), models.Index(fields=['severity', 'created_at'], name='users_audit_severit_6437a2_idx'), models.Index(fields=['target_type', 'target_id'], name='users_audit_target__15185f_idx'), models.Index(fields=['created_at'], name='users_audit_created_6518da_idx')],
            },
        ),
    ]
