# Generated by Django 5.2.6 on 2026-02-20 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universites', '0008_remove_news_publisher_remove_oldstudent_publisher_and_more'),
        ('users', '0020_alter_invitationcode_expires_at_auditlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='users_audit_user_id_0bc804_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_email_c80f75_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invitationcode',
            name='used_by',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Utilisateur'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='created_by_email',
            field=models.EmailField(default='admin@example.com', max_length=254, verbose_name='Créé par (email)'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='created_by_id',
            field=models.IntegerField(default=1, verbose_name='Créé par (ID)'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='used_by_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Utilisé par (email)'),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='used_by_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Utilisé par (ID)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_repr',
            field=models.TextField(blank=True, verbose_name='Représentation cible'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email utilisateur'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rôle utilisateur'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 17, 38, 31, 539565, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_id', 'created_at'], name='users_audit_user_id_0bc804_idx'),
        ),
    ]
