# Generated by Django 5.2.6 on 2026-02-20 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_auditlog_users_audit_user_id_0bc804_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='created_by_email',
            field=models.EmailField(max_length=254, verbose_name='Créé par (email)'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='created_by_id',
            field=models.IntegerField(verbose_name='Créé par (ID)'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 17, 39, 5, 545607, tzinfo=datetime.timezone.utc)),
        ),
    ]
