# Generated by Django 5.2.6 on 2026-02-25 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        ('memoires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='memoires.memoire'),
        ),
    ]
