# Generated by Django 5.2.6 on 2026-02-25 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0002_initial'),
        ('memoires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='memoires.memoire'),
        ),
        migrations.AddField(
            model_name='like',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telechargement',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to='memoires.memoire'),
        ),
        migrations.AddField(
            model_name='telechargement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('utilisateur', 'memoire')},
        ),
        migrations.AlterUniqueTogether(
            name='telechargement',
            unique_together={('utilisateur', 'memoire')},
        ),
    ]
