# Generated by Django 5.2.6 on 2026-02-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatHypotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='hypotheques/')),
            ],
        ),
        migrations.CreateModel(
            name='Cni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recto', models.ImageField(upload_to='cni/')),
                ('verso', models.ImageField(upload_to='cni/')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCadastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='plans/')),
            ],
        ),
        migrations.CreateModel(
            name='TitreFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='titres/')),
            ],
        ),
    ]
