# Generated by Django 5.2.6 on 2025-12-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roleuniversite',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_univ', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleuniversite',
            name='universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='universites.universite'),
        ),
        migrations.AddField(
            model_name='domaine',
            name='universites',
            field=models.ManyToManyField(blank=True, related_name='domaines', to='universites.universite'),
        ),
        migrations.AlterUniqueTogether(
            name='roleuniversite',
            unique_together={('utilisateur', 'universite')},
        ),
    ]
