# Generated by Django 5.2.6 on 2025-12-09 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universites', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique_for_date='publish_at')),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('cover', models.ImageField(blank=True, upload_to='news/%Y/%m')),
                ('topics', models.CharField(choices=[('general', 'Général'), ('event', 'Événement'), ('award', 'Récompense'), ('research', 'Recherche'), ('alumni', 'Alumni')], default='general', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(db_index=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='universites.universite')),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
    ]
