# Generated by Django 5.2.6 on 2025-12-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration): 

    dependencies = [
        ('universites', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='news_covers/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universites.universite'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='topics',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
