# Generated by Django 5.2.6 on 2025-12-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration): 

    dependencies = [
        ('universites', '0004_alter_news_options_alter_news_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universites.universite')),
            ],
        ),
    ]
