# Generated by Django 5.2.6 on 2025-12-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universites', '0005_oldstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldstudent',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='oldstudent_covers/'),
        ),
    ]
