# Generated by Django 5.2.6 on 2025-12-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universites', '0006_alter_oldstudent_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('universite_affiliee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='universites.universite')),
                ('universite_mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites_affiliees', to='universites.universite')),
            ],
            options={
                'unique_together': {('universite_mere', 'universite_affiliee')},
            },
        ),
    ]
