# Generated by Django 5.2.6 on 2025-12-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universites', '0007_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='oldstudent',
            name='publisher',
        ),
        migrations.AddField(
            model_name='news',
            name='publishers',
            field=models.ManyToManyField(to='universites.universite'),
        ),
        migrations.AddField(
            model_name='oldstudent',
            name='publishers',
            field=models.ManyToManyField(to='universites.universite'),
        ),
    ]
