# Generated by Django 5.2.6 on 2025-12-02 02:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMemoire',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('resume', models.TextField()),
                ('annee', models.PositiveIntegerField()),
                ('fichier_pdf', models.TextField(max_length=100)),
                ('images', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('auteur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical memoire',
                'verbose_name_plural': 'historical memoires',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('resume', models.TextField()),
                ('annee', models.PositiveIntegerField()),
                ('fichier_pdf', models.FileField(upload_to='memoires/pdfs/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='memoires/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires', to=settings.AUTH_USER_MODEL)),
                ('domaines', models.ManyToManyField(blank=True, related_name='memoires', to='universites.domaine')),
                ('universites', models.ManyToManyField(blank=True, related_name='memoires', to='universites.universite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements_memoires', to=settings.AUTH_USER_MODEL)),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements', to='memoires.memoire')),
            ],
            options={
                'unique_together': {('memoire', 'encadreur')},
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('spam', 'Spam'), ('inaproprié', 'Inapproprié'), ('erreur', 'Erreur de contenu'), ('copyright', 'Violation de copyright')], max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='memoires.memoire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('memoire', 'utilisateur')},
            },
        ),
    ]
