# Generated by Django 5.2.6 on 2025-12-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memoires', '0001_initial'),
        ('universites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encadrement',
            name='encadreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements_memoires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmemoire',
            name='auteur',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmemoire',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoire',
            name='domaines',
            field=models.ManyToManyField(blank=True, related_name='memoires', to='universites.domaine'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='universites',
            field=models.ManyToManyField(blank=True, related_name='memoires', to='universites.universite'),
        ),
        migrations.AddField(
            model_name='encadrement',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadrements', to='memoires.memoire'),
        ),
        migrations.AddField(
            model_name='notation',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='memoires.memoire'),
        ),
        migrations.AddField(
            model_name='notation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signalement',
            name='memoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='memoires.memoire'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='encadrement',
            unique_together={('memoire', 'encadreur')},
        ),
        migrations.AlterUniqueTogether(
            name='notation',
            unique_together={('memoire', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='signalement',
            unique_together={('memoire', 'utilisateur')},
        ),
    ]
